### ISSUE TITLE
Getting unknown property: yii\console\Request::url

### ISSUE THREAD

**Issue by rakkot-vm** [klisl/yii2-languages#1]
После установки невозможно пользоваться консолью yii, базовый шаблон 
http://joxi.ru/Y2L4QwKino1wD2

**Comment by victorsemenov** [comment]
./yii
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\Request::url'

in vendor/yiisoft/yii2/base/Component.php:148

Stack trace:
#0 /vendor/klisl/yii2-languages/src/Bootstrap.php(37): yii\base\Component->__get('url')
#1 /vendor/klisl/yii2-languages/src/Bootstrap.php(28): klisl\languages\Bootstrap->run(Object(yii\console\Application))
#2 /vendor/yiisoft/yii2/base/Application.php(297): klisl\languages\Bootstrap->bootstrap(Object(yii\console\Application))
#3 /vendor/yiisoft/yii2/base/Application.php(273): yii\base\Application->bootstrap()
#4 /vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#5 /vendor/yiisoft/yii2/base/BaseObject.php(108): yii\console\Application->init()
#6 /vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#7 /vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#8 /yii(19): yii\console\Application->__construct(Array)
#9 {main}

**Comment by rain12ab** [comment]
какие то решения по этому поводу?

**Comment by pkorniev** [comment]
А зачем в предзагрузке указывать компонент которого нет в приложении? В консольном приложении явно не может быть Request.
